-- Retro Craft Manager shared database
create extension if not exists pgcrypto;

create table workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table workspace_members (
  workspace_id uuid references workspaces(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','member')),
  primary key (workspace_id,user_id)
);

create table resources (
  id bigint generated by default as identity primary key,
  retro_id integer unique,
  name text not null,
  image_url text,
  unit_price bigint not null default 0
);

create table items (
  id bigint generated by default as identity primary key,
  retro_id integer unique,
  name text not null,
  level integer,
  type text,
  image_url text
);

create table recipes (
  item_id bigint references items(id) on delete cascade,
  resource_id bigint references resources(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  primary key(item_id,resource_id)
);

create table stock (
  workspace_id uuid references workspaces(id) on delete cascade,
  resource_id bigint references resources(id) on delete cascade,
  quantity integer not null default 0 check (quantity >= 0),
  updated_at timestamptz not null default now(),
  primary key(workspace_id,resource_id)
);

create table crafts (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid references workspaces(id) on delete cascade not null,
  item_id bigint references items(id) not null,
  quantity integer not null default 1 check (quantity > 0),
  status text not null default 'a_craft' check (status in ('a_craft','crafte','fm','en_vente','vendu')),
  sale_price bigint not null default 0,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table workspaces enable row level security;
alter table workspace_members enable row level security;
alter table stock enable row level security;
alter table crafts enable row level security;

create or replace function is_workspace_member(wid uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from workspace_members where workspace_id=wid and user_id=auth.uid());
$$;

create policy "members read workspaces" on workspaces for select using (is_workspace_member(id));
create policy "members read membership" on workspace_members for select using (is_workspace_member(workspace_id));
create policy "members manage stock" on stock for all using (is_workspace_member(workspace_id)) with check (is_workspace_member(workspace_id));
create policy "members manage crafts" on crafts for all using (is_workspace_member(workspace_id)) with check (is_workspace_member(workspace_id));

-- Public catalog is read-only from the client.
alter table resources enable row level security;
alter table items enable row level security;
alter table recipes enable row level security;
create policy "catalog read resources" on resources for select using (true);
create policy "catalog read items" on items for select using (true);
create policy "catalog read recipes" on recipes for select using (true);
